# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      Solution_Name: Ecommerce.sln                  
      Test_Project_Path: Ecommerce.Api.Products.Tests/Ecommerce.Api.Products.Tests.csproj 

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    # Install the .NET Core workload
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
        
    - name: Restore dependencies
      run: dotnet restore Ecommerce.sln
      
      
    - name: Build
      run: dotnet build --no-restore
      
      
    - name: Test
      run: dotnet test Ecommerce.Api.Products.Tests/Ecommerce.Api.Products.Tests.csproj --no-build --verbosity normal
